# Generated by Django 4.1.5 on 2023-01-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_marcas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marcas',
            new_name='Marca',
        ),
    ]
