# Generated by Django 4.1.5 on 2023-01-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='image',
            field=models.ImageField(upload_to='marca_img/'),
        ),
    ]
